### ISSUE TITLE
multipleimputer fit_transform gives error ( it is probably not finding indexes for sampling)

### ISSUE THREAD

**Issue by MrRobot2211** [kearnz/autoimpute#28] opened 2019-09-23 03:11 UTC
Hi. Ihave been trying to run the package but keep geting the following error,. To the best of my knowledge it has to be relates to not finding enough indexes to sample.

ValueError                                Traceback (most recent call last)
<ipython-input-702-c1a64737557f> in <module>
      1 auto_imputer=MultipleImputer(return_list=True)
----> 2 df_imp=auto_imputer.fit_transform(df_total)

~/anaconda3/lib/python3.7/site-packages/autoimpute/imputations/dataframe/multiple_imputer.py in fit_transform(self, X, y)
    229     def fit_transform(self, X, y=None):
    230         """Convenience method to fit then transform the same dataset."""
--> 231         return self.fit(X, y).transform(X)

~/anaconda3/lib/python3.7/site-packages/autoimpute/utils/checks.py in wrapper(d, *args, **kwargs)
     59             err = f"Neither {d_err} nor {a_err} are of type pd.DataFrame"
     60             raise TypeError(err)
---> 61         return func(d, *args, **kwargs)
     62     return wrapper
     63 

~/anaconda3/lib/python3.7/site-packages/autoimpute/utils/checks.py in wrapper(d, *args, **kwargs)
    124 
    125         # return func if no missingness violations detected, then return wrap
--> 126         return func(d, *args, **kwargs)
    127     return wrapper
    128 

~/anaconda3/lib/python3.7/site-packages/autoimpute/utils/checks.py in wrapper(d, *args, **kwargs)
    171             err = f"All values missing in column(s) {nc}. Should be removed."
    172             raise ValueError(err)
--> 173         return func(d, *args, **kwargs)
    174     return wrapper
    175 

~/anaconda3/lib/python3.7/site-packages/autoimpute/imputations/dataframe/multiple_imputer.py in transform(self, X)
    224                    for i in self.statistics_.items())
    225         if self.return_list:
--> 226             imputed = list(imputed)
    227         return imputed
    228 

~/anaconda3/lib/python3.7/site-packages/autoimpute/imputations/dataframe/multiple_imputer.py in <genexpr>(.0)
    222         # sequential only for now
    223         imputed = ((i[0], i[1].transform(X))
--> 224                    for i in self.statistics_.items())
    225         if self.return_list:
    226             imputed = list(imputed)

~/anaconda3/lib/python3.7/site-packages/autoimpute/utils/checks.py in wrapper(d, *args, **kwargs)
     59             err = f"Neither {d_err} nor {a_err} are of type pd.DataFrame"
     60             raise TypeError(err)
---> 61         return func(d, *args, **kwargs)
     62     return wrapper
     63 

~/anaconda3/lib/python3.7/site-packages/autoimpute/utils/checks.py in wrapper(d, *args, **kwargs)
    124 
    125         # return func if no missingness violations detected, then return wrap
--> 126         return func(d, *args, **kwargs)
    127     return wrapper
    128 

~/anaconda3/lib/python3.7/site-packages/autoimpute/utils/checks.py in wrapper(d, *args, **kwargs)
    171             err = f"All values missing in column(s) {nc}. Should be removed."
    172             raise ValueError(err)
--> 173         return func(d, *args, **kwargs)
    174     return wrapper
    175 

~/anaconda3/lib/python3.7/site-packages/autoimpute/imputations/dataframe/single_imputer.py in transform(self, X)
    251                     for col in x_m:
    252                         d = DefaultUnivarImputer()
--> 253                         d_imps = d.fit_impute(x_[col], None)
    254                         x_null = x_[col][x_[col].isnull()].index
    255                         x_.loc[x_null, col] = d_imps

~/anaconda3/lib/python3.7/site-packages/autoimpute/imputations/series/default.py in fit_impute(self, X, y)
    217     def fit_impute(self, X, y):
    218         """Convenience method to perform fit and imputation in one go."""
--> 219         return self.fit(X, y).impute(X)
    220 
    221 class DefaultUnivarImputer(DefaultBaseImputer):

~/anaconda3/lib/python3.7/site-packages/autoimpute/imputations/series/default.py in impute(self, X)
    276     def impute(self, X):
    277         """Defer transform to the DefaultBaseImputer."""
--> 278         X_ = super().impute(X)
    279         return X_
    280 

~/anaconda3/lib/python3.7/site-packages/autoimpute/imputations/series/default.py in impute(self, X)
    212         # ensure that param is not none, which indicates time series column
    213         if imp:
--> 214             X_ = imp.impute(X)
    215             return X_
    216 

~/anaconda3/lib/python3.7/site-packages/autoimpute/imputations/series/mode.py in impute(self, X)
    118                 imp = imp[0]
    119             else:
--> 120                 samples = np.random.choice(imp, len(ind))
    121                 imp = pd.Series(samples, index=ind).values
    122 

mtrand.pyx in mtrand.RandomState.choice()

ValueError: 'a' cannot be empty unless no samples are taken

**Comment by kearnz** [comment] 2019-09-24 02:10
Hi, from what I can deduce, you are using the `MultipleImputer` and at least one of the columns you are trying to impute is categorical. By default, the `MultipleImputer` uses the `mode` with `fill_strategy=='random'` to create placeholders (happy to expand on why, but out of scope for this error). In this case, there seems to be an issue imputing the mode itself as a placeholder value.

That being said, it's hard to say what exactly the issue is, as I cannot recreate it without the sample data. I tried to create some toy data but was not able to reproduce this way either. Can you share any more information about the dataframe? `auto_imputer.info()` perhaps? 

If the data is not sensitive, I can try to help using the data itself if you can share it. Let me know if that's a viable option.

**Comment by kearnz** [comment] 2019-11-16 17:05
closing unless further questions.

**Closed by kearnz** 2019-11-16 17:05 UTC
